name: shop_maikel
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  intl: ^0.16.1
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  avatar_glow: ^2.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.1"
  firebase_database: "^6.0.0"
  page_transition: "^2.0.2"
  material_design_icons_flutter: "^3.2.3895"
  font_awesome_flutter: ^8.8.1
  carousel_pro: ^1.0.0
  carousel_slider: "^4.0.0"
  firebase_storage: "^7.0.0"
  cloud_firestore: ^0.16.0+1
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/product-placeholder.png
    - assets/icons/Ammit.svg
    - assets/images/promotion__one.png
    - assets/images/promotion_two.png
    - assets/images/promotion_three.png
    - assets/icons/
    - assets/images/




  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf